# Generated by Django 3.2.7 on 2021-09-17 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConvertedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17)),
                ('year', models.IntegerField()),
                ('make', models.CharField(max_length=9)),
                ('model', models.CharField(max_length=14)),
                ('mileage', models.IntegerField()),
                ('color', models.CharField(max_length=5)),
                ('engine_size_liters', models.DecimalField(decimal_places=1, max_digits=2)),
                ('fuel_type', models.CharField(max_length=8)),
                ('avg_mpg', models.DecimalField(decimal_places=13, max_digits=15)),
                ('is_leased', models.BooleanField()),
            ],
        ),
    ]
